Mauriciogtec/issue14
NSAPH-Projects/space pull request #27
Opened 2023-03-24 01:32 UTC by mauriciogtec

- created data/make_dataset.py
- data/data.sh now downloads this file.
- removed the script portion from space/dataset.py

2023-03-30 19:15 UTC, atrisovic requested changes

2023-03-30 19:15 UTC, atrisovic commented on data/data.sh
> +fi
This should not be here because `make_dataset.py` will save the file at $user_path (or local path if $user_path is none).

2023-04-11 12:12 UTC, mauriciogtec commented
The code under `if [ "$user_path" != ".dataset_downloads" ]` is needed to consider the edge case when the user selects "$user_path" != ".dataset_downloads". Since there was a bug where everything was deleted after download due to using `rm <...>`.

2023-04-17 00:53 UTC, audiracmichelle commented
I think this specific PR should go into master because that branch will remain exclusively for readers of the CLeaR submission, correct?
all other spacebench package related PR will go to dev and then main? is this correct @Naeemkh ?

2023-04-17 01:20 UTC, Naeemkh commented
> I think this specific PR should go into master because that branch will remain exclusively for readers of the CLeaR submission, correct? all other spacebench package related PR will go to dev and then main? is this correct @Naeemkh ?

Yes. If it is related to old submission, it is better to be part of master branch. When you are done with that submission, we will drop the master branch and use the main branch.  @mauriciogtec, you can change the PR base branch.

2023-04-17 14:47 UTC, merged